name: ramadan_timetable
description: Offline Ramadan Timetable App
version: 1.0.0+1
environment:
 sdk: ">=3.0.0 <4.0.0"
dependencies:
 flutter:
  sdk: flutter
 shared_preferences: ^2.2.2
 flutter_local_notifications: ^17.1.2
 url_launcher: ^6.2.5
timezone: ^0.9.3
flutter:
 uses-material-design: true
 assets:
  - assets/data/
  - assets/audio/
  - assets/images/